---
workflows:
  - name: 'rabbitmq_to_mongo'
    description: "Consume broker payloads and store"
    location: "payler"
    callable: "client.process_queue"
  - name: "mongo_to_rabbitmq"
    description: "Poll storage and re-inject in RabbitMQ"
    callable: "client.watch_storage"
