---
name: "Release"

'on':
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  docker-image:
    name: "Publish docker image"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      - name: "Push to GitHub Packages"
        uses: "docker/build-push-action@v1"
        with:
          username: "${{ github.actor }}"
          password: "${{ secrets.CR_PAT }}"
          registry: ghcr.io
          repository: tbobm/payler
          tag_with_ref: true

  documentation:
    name: "Generate documentation"
    runs-on: "ubuntu-latest"
    needs:
      - linter
      - tests
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      - name: "Setup Python Environment"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"
      - name: "Install package"
        run: "pip install ."
      - name: "Install dev dependencies"
        run: "pip install -r requirements-doc.txt"
      - name: "Generate documentation"
        run: "make html"
      - name: "Deploy to gh pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT  }}
          publish_dir: ./build/html/
