---
name: "Run tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  base-ci:
    name: "Lint code and run unit tests"
    runs-on: "ubuntu-latest"
    services:
      mongo:
        image: "mongo:4.4"
        env:
          MONGO_INITDB_ROOT_USERNAME: payler
          MONGO_INITDB_ROOT_PASSWORD: secret
          MONGO_INITDB_DATABASE: payler
        ports:
          - "27017:27017"
      broker:
        image: "rabbitmq:3.8-management"
        env:
          RABBITMQ_DEFAULT_USER: payler
          RABBITMQ_DEFAULT_PASS: secret
          RABBITMQ_DEFAULT_VHOST: payler
        ports:
          - "5672:5672"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "Setup Python Environment"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"
      - name: "Install package"
        run: "pip install ."
      - name: "Install dev dependencies"
        run: "pip install -r requirements-dev.txt"
      - name: "Run tests"
        run: "python -m pytest --color=yes --cov payler --cov-report term tests/"
