---
name: "Run tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  base-ci:
    name: "Lint code and run unit tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "Setup Python Environment"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"
      - name: "Install package"
        run: "pip install ."
      - name: "Install dev dependencies"
        run: "pip install -r requirements-dev.txt"
      - name: "Run tests"
        run: "python -m pytest --color=yes --cov payler --cov-report term tests/"
